name: Build Binaries and Populate a Release

# Run a build when a new release is created (in draft mode)
on:
  release:
    types: [created]
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - name: echo git info
      run: |
        echo "GITHUB_REF: ${GITHUB_REF}"
        echo 'github.ref: ${{ github.ref }}'
        exit 2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: getDocker
      uses: actions/checkout@v2
      with:
        repository: docker/cli
        ref: ${{ github.ref }}
        persist-credentials: false

    - name: Build darwin
      uses: docker/bake-action@v1
      with:
        set: "binary.platform=darwin/amd64"

    - name: Build linux
      uses: docker/bake-action@v1
      with:
        set: "binary.platform=linux/amd64"

    - name: Check for Windows Fix from April, 2021
      run: |
        if !git merge-base --is-ancestor 04dad42c3c HEAD ; then
          echo "
        Applying the tiborvass fix (should be merged in v21+) ...
        "
          # Pull in the fixed file
          curl -o scripts/build/binary https://raw.githubusercontent.com/tiborvass/cli/83e9eeb8a08abd04a357c32f5fbf94129f569c71/scripts/build/binary
          # Tell git this file isn't dirty to avoid a `.m` version
          git update-index --assume-unchanged scripts/build/binary
        fi

    - name: Build on Windows
      uses: docker/bake-action@v1
      with:
        set: "binary.platform=windows/amd64"

    - name:  Calc SHAs
      working-directory: "./build"
      run: sha256sum docker-* > sha256sum.txt

    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      with:
        name: docker-darwin-amd64
        path: ./build/docker-darwin-amd64
        if-no-files-found: error

    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      with:
        name: docker-linux-amd64
        path: ./build/docker-linux-amd64
        if-no-files-found: error

    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      with:
        name: docker-windows-amd64
        path: ./build/docker-windows-amd64.exe
        if-no-files-found: error

    - uses: actions/upload-artifact@v2
      name: Upload checksums
      with:
        name: sha256sum.txt
        path: ./build/sha256sum.txt
        if-no-files-found: error

    - name: Add binaries to the release
      uses: skx/github-action-publish-binaries@b9ca5643b2f1d7371a6cba7f35333f1461bbc703
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: './build/docker-* ./build/sha256sum.txt'
